name: al_khatt_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  dio: ^5.9.0
  uuid: ^4.5.1
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  shared_preferences: ^2.5.3
  pinput: ^5.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.2.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Ù‡Ø°Ø§ Ù‡Ùˆ Ø§Ù„Ù…ÙƒØ§Ù† Ø§Ù„ØµØ­ÙŠØ­ Ù„Ù‡Ø°Ù‡ Ø§Ù„Ø­Ø²Ù…Ø©

flutter:
  uses-material-design: true

  # --- ØªØ¹Ø±ÙŠÙ Ù…Ø¬Ù„Ø¯Ø§Øª Ø§Ù„Ù…ÙˆØ§Ø±Ø¯ (Assets) ---
  assets:
    - assets/images/
    - assets/fonts/
    - assets/alkhat/
    - assets/alkhat/assets/
    - assets/alkhat/screens/

  # --- ØªØ¹Ø±ÙŠÙ Ø§Ù„Ø®Ø·ÙˆØ· Ø§Ù„Ù…Ø®ØµØµØ© (Custom Fonts) ---
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/alkhat/assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/alkhat/assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/alkhat/assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/alkhat/assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/alkhat/assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/alkhat/assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/alkhat/assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/alkhat/assets/fonts/Cairo-Black.ttf
          weight: 900

# --- Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ (ÙŠØ¬Ø¨ Ø£Ù† ØªÙƒÙˆÙ† Ù‡Ù†Ø§ ÙÙŠ Ù†Ù‡Ø§ÙŠØ© Ø§Ù„Ù…Ù„Ù) ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app_icon.png" # <--- ØªÙ… Ø§Ù„ØªØ¹Ø¯ÙŠÙ„ Ù‡Ù†Ø§
  min_sdk_android: 21
