# Generated by Django 5.2.8 on 2026-02-27 02:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('truck_small', 'Small Truck'), ('truck_medium', 'Medium Truck'), ('truck_large', 'Large Truck')], max_length=20)),
                ('is_registered_owner', models.BooleanField(default=True)),
                ('registration_reason', models.CharField(blank=True, max_length=200)),
                ('trailer_number', models.CharField(blank=True, max_length=40)),
                ('capacity_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_load_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
